[tool.pylint.messages_control]

disable = [
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "invalid-name",
    "too-few-public-methods"
]

[tool.flake8]
max-line-length = 119

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
multi_line_output = 3
length_sort = true
force_grid_wrap=0
line_length=88